Internal Server Error: /api/engagements/
Traceback (most recent call last):
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `montant_total_estime_mru` is not valid for model `Engagement`.
Internal Server Error: /api/engagements/
Traceback (most recent call last):
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `montant_total_estime_mru` is not valid for model `Engagement`.
[29/Oct/2025 23:16:34] "GET /api/engagements/?page=1&page_size=10 HTTP/1.1" 500 155597
[29/Oct/2025 23:16:34] "GET /api/engagements/?page=1&page_size=10 HTTP/1.1" 500 155597
[29/Oct/2025 23:16:37] "GET /api/engagements/mises_a_disposition_disponibles/ HTTP/1.1" 200 339
[29/Oct/2025 23:16:37] "GET /api/engagements/mises_a_disposition_disponibles/ HTTP/1.1" 200 339
[29/Oct/2025 23:16:47] "GET /api/fournisseurs/?page=1&page_size=10 HTTP/1.1" 200 4687
[29/Oct/2025 23:16:47] "GET /api/fournisseurs/?page=1&page_size=10 HTTP/1.1" 200 4687
Internal Server Error: /api/fiches-pointage/
Traceback (most recent call last):
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/eter/.local/share/Trash/files/eter-projectv1.0/eter_backend/apps/core/serializers.py", line 812, in get_total_heures_travail
    result = obj.pointages_journaliers.aggregate(total=Sum('heures_travail'))
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 459, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/aggregates.py", line 65, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/expressions.py", line 975, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/expressions.py", line 854, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 2014, in resolve_ref
    join_info = self.setup_joins(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1867, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'heures_travail' into field. Choices are: date_pointage, fiche_pointage, fiche_pointage_id, id
[29/Oct/2025 23:16:51] "GET /api/fiches-pointage/?page=1&page_size=10 HTTP/1.1" 500 194145
Internal Server Error: /api/fiches-pointage/
Traceback (most recent call last):
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/eter/.local/share/Trash/files/eter-projectv1.0/eter_backend/apps/core/serializers.py", line 812, in get_total_heures_travail
    result = obj.pointages_journaliers.aggregate(total=Sum('heures_travail'))
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 459, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/aggregates.py", line 65, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/expressions.py", line 975, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/expressions.py", line 854, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 2014, in resolve_ref
    join_info = self.setup_joins(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1867, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'heures_travail' into field. Choices are: date_pointage, fiche_pointage, fiche_pointage_id, id
[29/Oct/2025 23:16:51] "GET /api/fiches-pointage/?page=1&page_size=10 HTTP/1.1" 500 194145
Internal Server Error: /api/engagements/statistiques/
Traceback (most recent call last):
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/eter/.local/share/Trash/files/eter-projectv1.0/eter_backend/apps/core/views.py", line 784, in statistiques
    montant_total = queryset.aggregate(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 459, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/aggregates.py", line 65, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/expressions.py", line 975, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/expressions.py", line 854, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 2014, in resolve_ref
    join_info = self.setup_joins(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1867, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'montant_total_estime_mru' into field. Choices are: budget_previsionnel_mru, conditions_particulieres, created_at, date_debut, date_fin, fiches_pointage, id, mise_a_disposition, mise_a_disposition_id, montant_actuel_mru, numero, responsable, responsable_id
Internal Server Error: /api/engagements/statistiques/
Traceback (most recent call last):
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/eter/.local/share/Trash/files/eter-projectv1.0/eter_backend/apps/core/views.py", line 784, in statistiques
    montant_total = queryset.aggregate(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 459, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/aggregates.py", line 65, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/expressions.py", line 975, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/expressions.py", line 854, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 2014, in resolve_ref
    join_info = self.setup_joins(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1867, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'montant_total_estime_mru' into field. Choices are: budget_previsionnel_mru, conditions_particulieres, created_at, date_debut, date_fin, fiches_pointage, id, mise_a_disposition, mise_a_disposition_id, montant_actuel_mru, numero, responsable, responsable_id
[29/Oct/2025 23:16:57] "GET /api/engagements/statistiques/ HTTP/1.1" 500 141745
[29/Oct/2025 23:16:57] "GET /api/engagements/statistiques/ HTTP/1.1" 500 141745
Internal Server Error: /api/engagements/
Traceback (most recent call last):
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `montant_total_estime_mru` is not valid for model `Engagement`.
Internal Server Error: /api/engagements/
Traceback (most recent call last):
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/eter/Documents/eter project/eter-projectv1.0/eter_backend/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(